import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


_HEADER = "<!-- generated by skills/migration-fanout/progress.py from waves/*.result.json; do not edit -->"
_TABLE_HEADER = "| wave | batch | unit | status | recon_verdict | verifier_verdict | pr_url | merged | batch_recon_cost |"
_TABLE_DIVIDER = "|---|---|---|---|---|---|---|---|---|"
_WAVE_NAME = re.compile(r"wave-(\d+)\.result\.json$")
_RESULT_SUFFIX = ".result.json"


def _text(value) -> str:
    return "" if value is None else str(value)


def _bool(value) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    return _text(value)


def _wave_key(value):
    return (0, value) if isinstance(value, int) and not isinstance(value, bool) else (1, _text(value))


def _wave(result: dict, path: Path):
    wave = result.get("wave")
    if wave is not None:
        return wave
    match = _WAVE_NAME.fullmatch(path.name)
    return int(match.group(1)) if match else ""


def _manifest_units(path: Path, expected_sha) -> dict:
    manifest_path = path.with_name(path.name[:-len(_RESULT_SUFFIX)] + ".json")
    if not manifest_path.is_file():
        raise ValueError(f"{manifest_path}: manifest is missing")
    try:
        manifest_bytes = manifest_path.read_bytes()
    except OSError as exc:
        raise ValueError(f"{manifest_path}: manifest is unreadable") from exc
    actual_sha = hashlib.sha256(manifest_bytes).hexdigest()[:12]
    if not isinstance(expected_sha, str) or expected_sha != actual_sha:
        raise ValueError(f"{manifest_path}: manifest_sha does not match the manifest")
    try:
        manifest = json.loads(manifest_bytes)
    except (UnicodeDecodeError, ValueError) as exc:
        raise ValueError(f"{manifest_path}: manifest is unreadable") from exc
    if not isinstance(manifest, dict):
        raise ValueError(f"{manifest_path}: manifest is not an object")
    batches = manifest.get("batches")
    if not isinstance(batches, list):
        raise ValueError(f"{manifest_path}: manifest batches is not a list")
    units = {}
    for batch in batches:
        if not isinstance(batch, dict):
            raise ValueError(f"{manifest_path}: manifest batch is not an object")
        batch_id = batch.get("id")
        batch_units = batch.get("units")
        if batch_units is None:
            continue
        if not isinstance(batch_units, list):
            raise ValueError(f"{manifest_path}: manifest batch {batch_id!r} units is not a list")
        if batch_id not in (None, ""):
            units[_text(batch_id)] = batch_units
    return units


def _merged_path(path: Path) -> Path:
    return path.with_name(path.name[:-len(_RESULT_SUFFIX)] + ".merged.json")


def _merged_record(path: Path):
    merged_path = _merged_path(path)
    if not merged_path.is_file():
        return None
    try:
        record = json.loads(merged_path.read_text())
    except (OSError, UnicodeDecodeError, ValueError):
        raise ValueError(f"{merged_path}: merged record is not an object") from None
    if not isinstance(record, dict):
        raise ValueError(f"{merged_path}: merged record is not an object")
    if not isinstance(record.get("merged"), dict):
        raise ValueError(f"{merged_path}: merged record merged is not a dict")
    return record


def _result(path: Path) -> dict:
    try:
        result = json.loads(path.read_text())
    except (OSError, UnicodeDecodeError, ValueError):
        raise ValueError(f"{path}: not a JSON object") from None
    if not isinstance(result, dict):
        raise ValueError(f"{path}: not a JSON object")
    return result


def _refresh_base_branch(path: Path):
    manifest_path = path.with_name(path.name[:-len(_RESULT_SUFFIX)] + ".json")
    if not manifest_path.is_file():
        print(f"{path}: skipping merged refresh; manifest base_branch is missing", file=sys.stderr)
        return None
    try:
        manifest = json.loads(manifest_path.read_text())
    except (OSError, UnicodeDecodeError, ValueError):
        raise ValueError(f"{manifest_path}: manifest is unreadable") from None
    if not isinstance(manifest, dict):
        raise ValueError(f"{manifest_path}: manifest is not an object")
    base_branch = manifest.get("base_branch")
    if not isinstance(base_branch, str) or not base_branch:
        print(f"{path}: skipping merged refresh; manifest base_branch is missing", file=sys.stderr)
        return None
    return base_branch


def refresh_merged(mig: Path) -> None:
    waves = mig / "waves"
    repo = mig.parent
    for path in sorted(waves.glob("*.result.json")):
        result = _result(path)
        if result.get("auto_merge") is not False:
            continue
        if not isinstance(result.get("batches"), list):
            raise ValueError(f"{path}: result batches is not a list")
        verify = result.get("verify")
        if verify is not None and not isinstance(verify, dict):
            raise ValueError(f"{path}: verify is not a dict")
        merged_prs = verify.get("merged_prs") if isinstance(verify, dict) else None
        if merged_prs is not None and not isinstance(merged_prs, list):
            raise ValueError(f"{path}: verify merged_prs is not a list")
        merged_prs = merged_prs or []
        candidates = [
            (batch.get("pr_url"), batch.get("pr_head"))
            for batch in result["batches"]
            if isinstance(batch, dict)
            and _text(batch.get("status")) == "PASS"
            and isinstance(batch.get("pr_url"), str)
            and batch.get("pr_url")
            and isinstance(batch.get("pr_head"), str)
            and batch.get("pr_head")
            and batch.get("pr_url") not in merged_prs
        ]
        merged_record = _merged_record(path)
        if not candidates:
            continue
        base_branch = _refresh_base_branch(path)
        if base_branch is None:
            continue
        fetch = subprocess.run(
            [
                "git", "-C", str(repo), "fetch", "-q", "origin",
                f"+refs/heads/{base_branch}:refs/remotes/origin/{base_branch}",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        if fetch.returncode != 0:
            raise subprocess.CalledProcessError(fetch.returncode, fetch.args, fetch.stdout, fetch.stderr)
        base_sha = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", f"origin/{base_branch}"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        merged = dict(merged_record["merged"]) if merged_record is not None else {}
        for pr_url, pr_head in candidates:
            merged_head = subprocess.run(
                ["git", "-C", str(repo), "merge-base", "--is-ancestor", pr_head, f"origin/{base_branch}"],
                check=False,
                capture_output=True,
            )
            if merged_head.returncode == 0:
                merged[pr_url] = pr_head
            elif merged_head.returncode != 1:
                raise subprocess.SubprocessError(
                    f"merge-base rc={merged_head.returncode} for {pr_head}"
                )
        if merged or merged_record is not None:
            _merged_path(path).write_text(json.dumps(
                {"base": base_sha, "merged": merged},
                sort_keys=True,
                indent=2,
            ) + "\n")


def render_progress(mig: Path) -> str:
    waves = mig / "waves"
    results = []
    for path in sorted(waves.glob("*.result.json")):
        try:
            result = _result(path)
        except ValueError:
            raise
        results.append((result, path))

    rows = []
    for result, path in results:
        wave = _wave(result, path)
        if not isinstance(result.get("batches"), list):
            raise ValueError(f"{path}: result batches is not a list")
        merged_record = _merged_record(path)
        merged_record_entries = merged_record.get("merged", {}) if merged_record else {}
        verify = result.get("verify")
        if verify is not None and not isinstance(verify, dict):
            raise ValueError(f"{path}: verify is not a dict")
        unit_verdicts = verify.get("unit_verdicts") if isinstance(verify, dict) else None
        if unit_verdicts is not None and not isinstance(unit_verdicts, dict):
            raise ValueError(f"{path}: verify unit_verdicts is not a dict")
        merged_prs = verify.get("merged_prs") if isinstance(verify, dict) else None
        if merged_prs is not None and not isinstance(merged_prs, list):
            raise ValueError(f"{path}: verify merged_prs is not a list")
        manifest_units = None
        for batch in result["batches"]:
            if not isinstance(batch, dict):
                raise ValueError(f"{path}: result batch is not an object")
            batch_id = batch.get("id")
            if batch_id in (None, ""):
                raise ValueError(f"{path}: result batch has no id")
            batch_id = _text(batch_id)
            cost = batch.get("recon_cost")
            cost_text = json.dumps(cost, sort_keys=True, separators=(",", ":")) \
                if isinstance(cost, dict) else ""
            units = batch.get("units")
            if not isinstance(units, list):
                if manifest_units is None:
                    try:
                        manifest_units = _manifest_units(path, result.get("manifest_sha"))
                    except ValueError as exc:
                        if "manifest_sha does not match the manifest" in str(exc):
                            raise ValueError(
                                f"{path}: batch {batch.get('id')!r} has no units and manifest_sha does not match the manifest "
                                "(embed units in the result or regenerate it)"
                            ) from None
                        raise ValueError(
                            f"{path}: batch {batch.get('id')!r} has no units and no readable manifest entry"
                        ) from None
                units = manifest_units.get(batch_id)
                if not isinstance(units, list):
                    raise ValueError(
                        f"{path}: batch {batch_id!r} has no units and no readable manifest entry"
                    )
            if not units:
                raise ValueError(f"{path}: batch {batch_id!r} has no units")
            verifier_verdict = (
                _text(unit_verdicts[batch_id])
                if isinstance(unit_verdicts, dict) and batch_id in unit_verdicts
                else ""
            )
            status = (
                verifier_verdict
                if verifier_verdict
                else "UNVERIFIED"
                if isinstance(verify, dict) and _text(batch.get("status")) == "PASS"
                else _text(batch.get("status"))
            )
            pr_url = batch.get("pr_url")
            record_head = (
                merged_record_entries.get(pr_url)
                if isinstance(pr_url, str) and pr_url
                else None
            )
            merged = (
                "yes"
                if isinstance(pr_url, str) and pr_url and isinstance(merged_prs, list) and pr_url in merged_prs
                or isinstance(record_head, str) and record_head and record_head == batch.get("pr_head")
                else "pending"
                if status == "PASS"
                else ""
            )
            for unit_index, unit in enumerate(sorted(units, key=_text)):
                rows.append((
                    wave,
                    _text(batch_id),
                    _text(unit),
                    status,
                    _text(batch.get("recon_verdict")),
                    verifier_verdict,
                    _text(pr_url),
                    merged,
                    cost_text if unit_index == 0 else "",
                ))
    rows.sort(key=lambda row: (_wave_key(row[0]), row[1], row[2]))

    lines = [_HEADER, _TABLE_HEADER, _TABLE_DIVIDER]
    lines.extend("| " + " | ".join(_text(value) for value in row) + " |" for row in rows)
    for result, path in sorted(results, key=lambda item: _wave_key(_wave(*item))):
        wave = _wave(result, path)
        breaker = result.get("breaker_tripped_on") or "-"
        lines.append(
            f"wave {wave}: closed={_bool(result.get('closed'))}, "
            f"auto_merge={_bool(result.get('auto_merge'))}, breaker_tripped_on={breaker}"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("migration_dir", type=Path)
    parser.add_argument("--refresh-merged", action="store_true")
    args = parser.parse_args(argv)
    if args.refresh_merged:
        refresh_merged(args.migration_dir)
    output = args.migration_dir / "05_progress.md"
    output.write_text(render_progress(args.migration_dir))
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
