import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


_HEADER = "<!-- generated by skills/migration-fanout/progress.py from waves/*.result.json; do not edit -->"
_TABLE_HEADER = "| wave | batch | unit | status | recon_verdict | verifier_verdict | pr_url | merged | batch_recon_cost |"
_TABLE_DIVIDER = "|---|---|---|---|---|---|---|---|---|"
_WAVE_NAME = re.compile(r"wave-(\d+)\.result\.json$")
_RESULT_SUFFIX = ".result.json"


def _text(value) -> str:
    return "" if value is None else str(value)


def _bool(value) -> str:
    if isinstance(value, bool):
        return str(value).lower()
    return _text(value)


def _wave_key(value):
    return (0, value) if isinstance(value, int) and not isinstance(value, bool) else (1, _text(value))


def _wave(result: dict, path: Path):
    wave = result.get("wave")
    if wave is not None:
        return wave
    match = _WAVE_NAME.fullmatch(path.name)
    return int(match.group(1)) if match else ""


def _manifest_bytes(path: Path, expected_sha):
    manifest_path = path.with_name(path.name[:-len(_RESULT_SUFFIX)] + ".json")
    if not manifest_path.is_file():
        raise ValueError(f"{manifest_path}: manifest is missing")
    try:
        manifest_bytes = manifest_path.read_bytes()
    except OSError as exc:
        raise ValueError(f"{manifest_path}: manifest is unreadable") from exc
    actual_sha = hashlib.sha256(manifest_bytes).hexdigest()[:12]
    if not isinstance(expected_sha, str) or expected_sha != actual_sha:
        raise ValueError(f"{manifest_path}: manifest_sha does not match the manifest")
    return manifest_path, manifest_bytes


def _manifest(manifest_path: Path, manifest_bytes: bytes) -> dict:
    try:
        manifest = json.loads(manifest_bytes)
    except (UnicodeDecodeError, ValueError) as exc:
        raise ValueError(f"{manifest_path}: manifest is unreadable") from exc
    if not isinstance(manifest, dict):
        raise ValueError(f"{manifest_path}: manifest is not an object")
    return manifest


def _manifest_units(manifest_path: Path, manifest: dict) -> dict:
    batches = manifest.get("batches")
    if not isinstance(batches, list):
        raise ValueError(f"{manifest_path}: manifest batches is not a list")
    units = {}
    for batch in batches:
        if not isinstance(batch, dict):
            raise ValueError(f"{manifest_path}: manifest batch is not an object")
        batch_id = batch.get("id")
        if batch_id in (None, ""):
            raise ValueError(f"{manifest_path}: manifest batch has no id")
        batch_units = batch.get("units")
        if not isinstance(batch_units, list):
            raise ValueError(f"{manifest_path}: manifest batch {batch_id!r} has no units")
        batch_id = _text(batch_id)
        if batch_id in units:
            raise ValueError(f"{manifest_path}: duplicate batch id {batch_id!r}")
        units[batch_id] = batch_units
    return units


def _merged_path(path: Path) -> Path:
    return path.with_name(path.name[:-len(_RESULT_SUFFIX)] + ".merged.json")


def _merged_record(path: Path):
    merged_path = _merged_path(path)
    if not merged_path.is_file():
        return None
    try:
        record = json.loads(merged_path.read_text())
    except (OSError, UnicodeDecodeError, ValueError):
        raise ValueError(f"{merged_path}: merged record is not an object") from None
    if not isinstance(record, dict):
        raise ValueError(f"{merged_path}: merged record is not an object")
    if not isinstance(record.get("merged"), dict):
        raise ValueError(f"{merged_path}: merged record merged is not a dict")
    return record


def _result(path: Path) -> dict:
    try:
        result = json.loads(path.read_text())
    except (OSError, UnicodeDecodeError, ValueError):
        raise ValueError(f"{path}: not a JSON object") from None
    if not isinstance(result, dict):
        raise ValueError(f"{path}: not a JSON object")
    return result


def _patch_lines(diff_text: str) -> list:
    return [
        line for line in diff_text.splitlines()
        if line[:1] in "+-" and not line.startswith(("+++", "---"))
    ]


def _landed(repo: Path, pr_head: str, base_ref: str) -> bool:
    head_check = subprocess.run(
        ["git", "-C", str(repo), "cat-file", "-e", f"{pr_head}^{{commit}}"],
        check=False,
        capture_output=True,
    )
    if head_check.returncode != 0:
        subprocess.run(
            ["git", "-C", str(repo), "fetch", "-q", "origin", pr_head],
            check=False,
            capture_output=True,
        )
        head_check = subprocess.run(
            ["git", "-C", str(repo), "cat-file", "-e", f"{pr_head}^{{commit}}"],
            check=False,
            capture_output=True,
        )
    if head_check.returncode == 0:
        merged_head = subprocess.run(
            ["git", "-C", str(repo), "merge-base", "--is-ancestor", pr_head, base_ref],
            check=False,
            capture_output=True,
        )
        if merged_head.returncode == 0:
            return True
        if merged_head.returncode != 1:
            raise subprocess.SubprocessError(
                f"merge-base rc={merged_head.returncode} for {pr_head}"
            )

        merge_base = subprocess.run(
            ["git", "-C", str(repo), "merge-base", base_ref, pr_head],
            check=False,
            capture_output=True,
            text=True,
        )
        if merge_base.returncode == 0:
            mb = merge_base.stdout.strip()
            diff = subprocess.run(
                ["git", "-C", str(repo), "diff", mb, pr_head],
                check=False,
                capture_output=True,
                text=True,
            )
            if diff.returncode == 0:
                patch_id = subprocess.run(
                    ["git", "-C", str(repo), "patch-id", "--stable"],
                    check=False,
                    capture_output=True,
                    text=True,
                    input=diff.stdout,
                )
                pid = patch_id.stdout.split()[0] if patch_id.returncode == 0 and patch_id.stdout.split() else ""
                if pid:
                    pr_patches = []
                    pr_commits = subprocess.run(
                        ["git", "-C", str(repo), "rev-list", "--reverse", f"{mb}..{pr_head}"],
                        check=False,
                        capture_output=True,
                        text=True,
                    )
                    if pr_commits.returncode == 0:
                        for commit in pr_commits.stdout.splitlines():
                            commit_diff = subprocess.run(
                                ["git", "-C", str(repo), "diff-tree", "-p", "--root", commit],
                                check=False,
                                capture_output=True,
                                text=True,
                            )
                            if commit_diff.returncode != 0:
                                continue
                            commit_patch_id = subprocess.run(
                                ["git", "-C", str(repo), "patch-id", "--stable"],
                                check=False,
                                capture_output=True,
                                text=True,
                                input=commit_diff.stdout,
                            )
                            if commit_patch_id.returncode == 0 and commit_patch_id.stdout.split():
                                pr_patches.append(
                                    (
                                        commit_patch_id.stdout.split()[0],
                                        _patch_lines(commit_diff.stdout),
                                    )
                                )
                    commits = subprocess.run(
                        ["git", "-C", str(repo), "rev-list", "-n", "500", base_ref, f"^{mb}"],
                        check=False,
                        capture_output=True,
                        text=True,
                    )
                    if commits.returncode == 0:
                        base_patches = {}
                        for commit in commits.stdout.splitlines():
                            commit_diff = subprocess.run(
                                ["git", "-C", str(repo), "diff-tree", "-p", "--root", commit],
                                check=False,
                                capture_output=True,
                                text=True,
                            )
                            if commit_diff.returncode != 0:
                                continue
                            commit_patch_id = subprocess.run(
                                ["git", "-C", str(repo), "patch-id", "--stable"],
                                check=False,
                                capture_output=True,
                                text=True,
                                input=commit_diff.stdout,
                            )
                            if (
                                commit_patch_id.returncode == 0
                                and commit_patch_id.stdout.split()
                            ):
                                base_patches[commit_patch_id.stdout.split()[0]] = _patch_lines(
                                    commit_diff.stdout
                                )
                        if base_patches.get(pid) == _patch_lines(diff.stdout):
                            return True
                        if pr_patches and all(
                            base_patches.get(commit_pid) == commit_lines
                            for commit_pid, commit_lines in pr_patches
                        ) and len(pr_patches) == len(pr_commits.stdout.splitlines()):
                            return True

    return False


def refresh_merged(mig: Path) -> None:
    waves = mig / "waves"
    repo = mig.parent
    refreshes = []
    for path in sorted(waves.glob("*.result.json")):
        result = _result(path)
        if result.get("auto_merge") is not False:
            continue
        if not isinstance(result.get("batches"), list):
            raise ValueError(f"{path}: result batches is not a list")
        verify = result.get("verify")
        if verify is not None and not isinstance(verify, dict):
            raise ValueError(f"{path}: verify is not a dict")
        merged_prs = verify.get("merged_prs") if isinstance(verify, dict) else None
        if merged_prs is not None and not isinstance(merged_prs, list):
            raise ValueError(f"{path}: verify merged_prs is not a list")
        merged_prs = merged_prs or []
        candidates = [
            (batch.get("pr_url"), batch.get("pr_head"))
            for batch in result["batches"]
            if isinstance(batch, dict)
            and _text(batch.get("status")) == "PASS"
            and isinstance(batch.get("pr_url"), str)
            and batch.get("pr_url")
            and isinstance(batch.get("pr_head"), str)
            and batch.get("pr_head")
            and batch.get("pr_url") not in merged_prs
        ]
        merged_record = _merged_record(path)
        manifest_path, manifest_bytes = _manifest_bytes(path, result.get("manifest_sha"))
        manifest = _manifest(manifest_path, manifest_bytes)
        base_branch = manifest.get("base_branch")
        if not isinstance(base_branch, str) or not base_branch:
            print(f"{path}: skipping merged refresh; manifest base_branch is missing", file=sys.stderr)
            continue
        refreshes.append((path, candidates, merged_record, base_branch))

    for path, candidates, merged_record, base_branch in refreshes:
        if not candidates:
            continue
        fetch = subprocess.run(
            [
                "git", "-C", str(repo), "fetch", "-q", "origin",
                f"+refs/heads/{base_branch}:refs/remotes/origin/{base_branch}",
            ],
            check=False,
            capture_output=True,
            text=True,
        )
        if fetch.returncode != 0:
            raise subprocess.CalledProcessError(fetch.returncode, fetch.args, fetch.stdout, fetch.stderr)
        base_sha = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", f"origin/{base_branch}"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
        merged = {}
        for pr_url, pr_head in candidates:
            if _landed(repo, pr_head, f"origin/{base_branch}"):
                merged[pr_url] = pr_head
        if merged or merged_record is not None:
            _merged_path(path).write_text(json.dumps(
                {"base": base_sha, "merged": merged},
                sort_keys=True,
                indent=2,
            ) + "\n")


def render_progress(mig: Path) -> str:
    waves = mig / "waves"
    results = []
    for path in sorted(waves.glob("*.result.json")):
        result = _result(path)
        results.append((result, path))

    rows = []
    for result, path in results:
        if not isinstance(result.get("batches"), list):
            raise ValueError(f"{path}: result batches is not a list")
        try:
            manifest_path, manifest_bytes = _manifest_bytes(path, result.get("manifest_sha"))
        except ValueError as exc:
            if "manifest_sha does not match the manifest" in str(exc):
                raise ValueError(
                    f"{path}: manifest_sha does not match the manifest (regenerate the result)"
                ) from None
            raise
        manifest = _manifest(manifest_path, manifest_bytes)
        manifest_wave = manifest.get("wave")
        if (
            not isinstance(manifest_wave, int)
            or isinstance(manifest_wave, bool)
            or manifest_wave < 0
        ):
            raise ValueError(
                f"{manifest_path}: manifest wave is not a non-negative integer"
            )
        filename_wave = _WAVE_NAME.fullmatch(path.name)
        if (
            ("wave" in result and result["wave"] != manifest_wave)
            or filename_wave is not None
            and int(filename_wave.group(1)) != manifest_wave
        ):
            raise ValueError(f"{path}: wave does not match the manifest")
        wave = manifest_wave
        merged_record = _merged_record(path)
        merged_record_entries = merged_record.get("merged", {}) if merged_record else {}
        verify = result.get("verify")
        if verify is not None and not isinstance(verify, dict):
            raise ValueError(f"{path}: verify is not a dict")
        unit_verdicts = verify.get("unit_verdicts") if isinstance(verify, dict) else None
        if unit_verdicts is not None and not isinstance(unit_verdicts, dict):
            raise ValueError(f"{path}: verify unit_verdicts is not a dict")
        merged_prs = verify.get("merged_prs") if isinstance(verify, dict) else None
        if merged_prs is not None and not isinstance(merged_prs, list):
            raise ValueError(f"{path}: verify merged_prs is not a list")
        manifest_units = _manifest_units(manifest_path, manifest)
        result_batches = {}
        result_order = []
        for batch in result["batches"]:
            if not isinstance(batch, dict):
                raise ValueError(f"{path}: result batch is not an object")
            batch_id = batch.get("id")
            if batch_id in (None, ""):
                raise ValueError(f"{path}: result batch has no id")
            batch_id = _text(batch_id)
            if batch_id in result_batches:
                raise ValueError(f"{path}: duplicate batch id {batch_id!r}")
            result_batches[batch_id] = batch
            result_order.append((batch_id, batch))

        for batch_id, units in manifest_units.items():
            if not units:
                raise ValueError(f"{path}: batch {batch_id!r} has no units")
            batch = result_batches.get(batch_id)
            embedded_units = batch.get("units") if batch is not None else None
            if isinstance(embedded_units, list):
                embedded_ids = {_text(unit) for unit in embedded_units}
                planned_ids = {_text(unit) for unit in units}
                unplanned_units = [
                    unit for unit in embedded_units if _text(unit) not in planned_ids
                ]
            else:
                unplanned_units = []
            if batch is None:
                for unit in units:
                    rows.append((wave, batch_id, _text(unit), "MISSING", "", "", "", "", ""))
                continue
            cost = batch.get("recon_cost")
            cost_text = json.dumps(cost, sort_keys=True, separators=(",", ":")) \
                if isinstance(cost, dict) else ""
            verifier_verdict = (
                _text(unit_verdicts[batch_id])
                if isinstance(unit_verdicts, dict) and batch_id in unit_verdicts
                else ""
            )
            batch_status = _text(batch.get("status"))
            status = (
                verifier_verdict
                if batch_status == "PASS" and verifier_verdict
                else "UNVERIFIED"
                if batch_status == "PASS"
                else batch_status
            )
            pr_url = batch.get("pr_url")
            record_head = (
                merged_record_entries.get(pr_url)
                if isinstance(pr_url, str) and pr_url
                else None
            )
            merged = (
                "yes"
                if isinstance(pr_url, str) and pr_url and isinstance(merged_prs, list) and pr_url in merged_prs
                or isinstance(record_head, str) and record_head and record_head == batch.get("pr_head")
                else "pending"
                if status == "PASS"
                else ""
            )
            if result.get("auto_merge") is False and status == "PASS" and merged != "yes":
                status = "PASS (unmerged)"
            normal_index = 0
            for unit in units:
                if isinstance(embedded_units, list) and _text(unit) not in embedded_ids:
                    rows.append((wave, batch_id, _text(unit), "MISSING", "", "", "", "", ""))
                    continue
                rows.append((
                    wave,
                    batch_id,
                    _text(unit),
                    status,
                    _text(batch.get("recon_verdict")),
                    verifier_verdict,
                    _text(pr_url),
                    merged,
                    cost_text if normal_index == 0 else "",
                ))
                normal_index += 1
            for unit in unplanned_units:
                rows.append((wave, batch_id, _text(unit), "UNPLANNED", "", "", "", "", ""))
        for batch_id, batch in result_order:
            if batch_id in manifest_units:
                continue
            embedded_units = batch.get("units")
            if not isinstance(embedded_units, list):
                raise ValueError(f"{path}: batch {batch_id!r} is not in the manifest")
            for unit in embedded_units:
                rows.append((wave, batch_id, _text(unit), "UNPLANNED", "", "", "", "", ""))

    rows.sort(key=lambda row: _wave_key(row[0]))

    lines = [_HEADER, _TABLE_HEADER, _TABLE_DIVIDER]
    lines.extend("| " + " | ".join(_text(value) for value in row) + " |" for row in rows)
    for result, path in sorted(results, key=lambda item: _wave_key(_wave(*item))):
        wave = _wave(result, path)
        breaker = result.get("breaker_tripped_on") or "-"
        lines.append(
            f"wave {wave}: closed={_bool(result.get('closed'))}, "
            f"auto_merge={_bool(result.get('auto_merge'))}, breaker_tripped_on={breaker}"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("migration_dir", type=Path)
    parser.add_argument("--refresh-merged", action="store_true")
    args = parser.parse_args(argv)
    if args.refresh_merged:
        refresh_merged(args.migration_dir)
    output = args.migration_dir / "05_progress.md"
    output.write_text(render_progress(args.migration_dir))
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
