import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from progress import main, render_progress


def _write_result(mig, name, result):
    waves = mig / "waves"
    waves.mkdir(parents=True, exist_ok=True)
    (waves / name).write_text(json.dumps(result))


def test_render_progress_sorts_rows_and_lists_wave_status(tmp_path):
    mig = tmp_path / ".migration"
    _write_result(mig, "wave-2.result.json", {
        "wave": 2,
        "closed": False,
        "auto_merge": True,
        "breaker_tripped_on": "timeout",
        "batches": [
            {"id": "b", "units": ["u2", "u1"], "status": "PASS",
             "recon_verdict": "PASS", "recon_cost": {"rows": 2}},
        ],
    })
    _write_result(mig, "wave-1.result.json", {
        "wave": 1,
        "closed": True,
        "auto_merge": False,
        "batches": [
            {"id": "z", "units": ["u3"], "status": "FAIL", "recon_verdict": "FAIL"},
            {"id": "a", "units": ["u2"], "status": "PASS", "recon_verdict": "PASS",
             "pr_url": "https://example.invalid/2"},
        ],
    })

    lines = render_progress(mig).splitlines()

    assert lines[0].startswith("<!-- generated by skills/migration-fanout/progress.py")
    assert lines[1] == "| wave | batch | unit | status | recon_verdict | pr_url | recon_cost |"
    assert "| 1 | a | u2 | PASS | PASS | https://example.invalid/2 |  |" in lines
    assert '| 2 | b | u1 | PASS | PASS |  | {"rows":2} |' in lines
    assert lines.index("| 1 | a | u2 | PASS | PASS | https://example.invalid/2 |  |") < \
        lines.index("| 1 | z | u3 | FAIL | FAIL |  |  |")
    assert "wave 1: closed=true, auto_merge=false, breaker_tripped_on=-" in lines
    assert "wave 2: closed=false, auto_merge=true, breaker_tripped_on=timeout" in lines


def test_render_progress_empty_waves_has_header_and_table(tmp_path):
    text = render_progress(tmp_path / ".migration")

    assert text.splitlines() == [
        "<!-- generated by skills/migration-fanout/progress.py from waves/*.result.json; do not edit -->",
        "| wave | batch | unit | status | recon_verdict | pr_url | recon_cost |",
        "|---|---|---|---|---|---|---|",
    ]


def test_render_progress_skips_invalid_json(tmp_path):
    mig = tmp_path / ".migration"
    waves = mig / "waves"
    waves.mkdir(parents=True)
    (waves / "wave-1.result.json").write_text("{not json")
    (waves / "wave-2.result.json").write_text(json.dumps({
        "wave": 2, "batches": [], "closed": True, "auto_merge": False,
    }))

    text = render_progress(mig)

    assert "wave 2: closed=true, auto_merge=false, breaker_tripped_on=-" in text
    assert "wave 1:" not in text


def test_main_writes_progress_file(tmp_path, capsys):
    mig = tmp_path / ".migration"
    (mig / "waves").mkdir(parents=True)

    assert main([str(mig)]) == 0
    assert (mig / "05_progress.md").read_text().startswith(
        "<!-- generated by skills/migration-fanout/progress.py"
    )
    assert capsys.readouterr().out.strip() == str(mig / "05_progress.md")
