/* Source: uc-dw-migration-teradata-to-bigquery ddl/tables/01_dim_customer.sql (abridged, unchanged semantics) */

CREATE SET TABLE BANKING_DW.DIM_CUSTOMER, NO FALLBACK,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
(
    CUSTOMER_ID         INTEGER          NOT NULL,
    CUSTOMER_KEY        BIGINT           NOT NULL GENERATED ALWAYS AS IDENTITY
                                         (START WITH 1 INCREMENT BY 1),
    FIRST_NAME          VARCHAR(50)      NOT CASESPECIFIC NOT NULL,
    LAST_NAME           VARCHAR(50)      NOT CASESPECIFIC NOT NULL,
    DATE_OF_BIRTH       DATE FORMAT 'YYYY-MM-DD',
    GENDER              CHAR(1)          COMPRESS ('M', 'F', 'O'),
    EMAIL_ADDRESS       VARCHAR(100)     NOT CASESPECIFIC,
    ADDRESS_LINE_2      VARCHAR(100)     NOT CASESPECIFIC COMPRESS '',
    COUNTRY_CODE        CHAR(3)          NOT CASESPECIFIC DEFAULT 'NOR',
    CUSTOMER_SEGMENT    VARCHAR(20)      NOT CASESPECIFIC
                                         COMPRESS ('RETAIL', 'PREMIUM', 'PRIVATE', 'CORPORATE'),
    RISK_SCORE          DECIMAL(5,2),
    CREDIT_RATING       CHAR(3)          COMPRESS ('AAA', 'AA', 'A', 'BBB', 'BB', 'B', 'CCC'),
    KYC_STATUS          VARCHAR(15)      NOT CASESPECIFIC DEFAULT 'PENDING',
    ONBOARDING_DATE     DATE FORMAT 'YYYY-MM-DD' NOT NULL,
    IS_ACTIVE           BYTEINT          DEFAULT 1 COMPRESS (0, 1),
    EFFECTIVE_FROM      TIMESTAMP(0)     DEFAULT CURRENT_TIMESTAMP(0),
    EFFECTIVE_TO        TIMESTAMP(0)     DEFAULT TIMESTAMP '9999-12-31 23:59:59',
    CURRENT_FLAG        CHAR(1)          DEFAULT 'Y' COMPRESS ('Y', 'N'),
    ETL_BATCH_ID        BIGINT,
    ETL_INSERT_TS       TIMESTAMP(0)     DEFAULT CURRENT_TIMESTAMP(0)
)
UNIQUE PRIMARY INDEX UPI_CUSTOMER_KEY (CUSTOMER_KEY)
INDEX NUPI_CUSTOMER_ID (CUSTOMER_ID)
INDEX IDX_CUST_SEGMENT (CUSTOMER_SEGMENT)
PARTITION BY RANGE_N(ONBOARDING_DATE BETWEEN DATE '2000-01-01'
                                     AND     DATE '2030-12-31'
                                     EACH INTERVAL '1' YEAR);

COLLECT STATISTICS COLUMN (CUSTOMER_ID) ON BANKING_DW.DIM_CUSTOMER;
COLLECT STATISTICS COLUMN (CUSTOMER_SEGMENT) ON BANKING_DW.DIM_CUSTOMER;

COMMENT ON TABLE BANKING_DW.DIM_CUSTOMER IS 'SCD Type 2 customer dimension with KYC and risk attributes';
COMMENT ON COLUMN BANKING_DW.DIM_CUSTOMER.CUSTOMER_KEY IS 'Surrogate key for SCD Type 2';
