SELECT 'version' AS k, current_version().dbsql_version AS v
UNION ALL SELECT 'int_div', CAST(7 / 2 AS STRING) || ' ' || CAST(7 DIV 2 AS STRING)
UNION ALL SELECT 'dec_div', typeof(CAST(10.00 AS DECIMAL(10,2)) / 3) || ' ' || CAST(CAST(10.00 AS DECIMAL(10,2)) / 3 AS STRING)
UNION ALL SELECT 'dec_div2', typeof(CAST(10.00 AS DECIMAL(12,2)) / CAST(3 AS BIGINT)) || ' ' || CAST(CAST(10.00 AS DECIMAL(12,2)) / CAST(3 AS BIGINT) AS STRING)
UNION ALL SELECT 'avg_dec', (SELECT typeof(avg(x)) || ' ' || CAST(avg(x) AS STRING) FROM VALUES (CAST(1.00 AS DECIMAL(10,2))), (CAST(2.00 AS DECIMAL(10,2))), (CAST(2.00 AS DECIMAL(10,2))) t(x))
UNION ALL SELECT 'sum_dec', (SELECT typeof(sum(x)) FROM VALUES (CAST(1.00 AS DECIMAL(10,2))) t(x))
UNION ALL SELECT 'concat_null', coalesce('a' || CAST(NULL AS STRING), '<NULL>')
UNION ALL SELECT 'concat_ws_null', concat_ws('', 'a', CAST(NULL AS STRING))
UNION ALL SELECT 'round_half', CAST(round(2.5) AS STRING) || ' ' || CAST(round(-2.5) AS STRING) || ' ' || CAST(round(CAST(2.5 AS DOUBLE)) AS STRING) || ' ' || CAST(bround(2.5) AS STRING)
UNION ALL SELECT 'datediff_day', CAST(datediff(TIMESTAMP '2026-01-02 01:00:00', TIMESTAMP '2026-01-01 23:00:00') AS STRING) || ' ' || CAST(timestampdiff(DAY, TIMESTAMP '2026-01-01 23:00:00', TIMESTAMP '2026-01-02 01:00:00') AS STRING)
UNION ALL SELECT 'datediff_month', CAST(timestampdiff(MONTH, DATE '2026-01-31', DATE '2026-02-28') AS STRING) || ' ' || CAST(months_between(DATE '2026-02-28', DATE '2026-01-31') AS STRING)
UNION ALL SELECT 'ts_default_prec', typeof(TIMESTAMP '2026-01-01 00:00:00') || ' ' || typeof(current_timestamp()) || ' ' || typeof(TIMESTAMP_NTZ '2026-01-01 00:00:00')
UNION ALL SELECT 'char_pad_eq', CAST(CAST('ab' AS CHAR(4)) = CAST('ab  ' AS CHAR(4)) AS STRING) || ' ' || CAST(length(CAST('ab' AS CHAR(4))) AS STRING) || ' [' || CAST(CAST('ab' AS CHAR(4)) AS STRING) || ']' || ' ' || typeof(CAST('ab' AS CHAR(4)))
UNION ALL SELECT 'char_vs_varchar', CAST(CAST('ab' AS CHAR(4)) = 'ab' AS STRING)
UNION ALL SELECT 'rtrim_collate', CAST('ab  ' COLLATE UTF8_BINARY_RTRIM = 'ab' AS STRING)
UNION ALL SELECT 'substr_zero', '[' || substr('abcdef', 0, 3) || ']'
UNION ALL SELECT 'array_idx', CAST(array(10,20,30)[0] AS STRING) || ' ' || CAST(element_at(array(10,20,30), 1) AS STRING)
UNION ALL SELECT 'array_oob', CAST(try_element_at(array(10,20,30), 5) IS NULL AS STRING)
UNION ALL SELECT 'map_missing', CAST(element_at(map('a', 1), 'zz') IS NULL AS STRING)
UNION ALL SELECT 'approx_pct', (SELECT CAST(percentile_approx(x, 0.5) AS STRING) FROM VALUES (1.0), (2.0), (3.0), (4.0) t(x))
UNION ALL SELECT 'exact_pct', (SELECT CAST(percentile(x, 0.5) AS STRING) || ' ' || CAST(median(x) AS STRING) || ' ' || CAST(percentile_cont(0.5) WITHIN GROUP (ORDER BY x) AS STRING) FROM VALUES (1.0), (2.0), (3.0), (4.0) t(x))
UNION ALL SELECT 'approx_pct_type', (SELECT typeof(percentile_approx(x, 0.5)) || ' ' || typeof(percentile(x, 0.5)) FROM VALUES (CAST(1.0 AS DECIMAL(10,2))) t(x))
UNION ALL SELECT 'approx_distinct', (SELECT CAST(approx_count_distinct(x) AS STRING) FROM VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9),(10) t(x))
UNION ALL SELECT 'nulls_order', (SELECT array_join(array_agg(x) , ',', 'NULL') FROM (SELECT x FROM VALUES (2), (NULL), (1) t(x) ORDER BY x))
UNION ALL SELECT 'nulls_order_desc', (SELECT array_join(array_agg(x) , ',', 'NULL') FROM (SELECT x FROM VALUES (2), (NULL), (1) t(x) ORDER BY x DESC))
UNION ALL SELECT 'array_agg_null', (SELECT CAST(size(array_agg(x)) AS STRING) || ' ' || CAST(size(collect_list(x)) AS STRING) FROM VALUES (1), (NULL) t(x))
UNION ALL SELECT 'greatest_null', CAST(greatest(1, NULL) IS NULL AS STRING)
UNION ALL SELECT 'mod_neg', CAST(mod(-7, 3) AS STRING) || ' ' || CAST(-7 % 3 AS STRING) || ' ' || CAST(pmod(-7, 3) AS STRING)
UNION ALL SELECT 'div_zero', CAST(try_divide(1, 0) IS NULL AS STRING)
UNION ALL SELECT 'cast_bad', CAST(try_cast('x' AS INT) IS NULL AS STRING)
UNION ALL SELECT 'date_format', date_format(TIMESTAMP '2026-03-07 14:05:09', 'yyyy-MM-dd HH:mm E')
UNION ALL SELECT 'date_trunc_week', CAST(date_trunc('WEEK', DATE '2026-03-08') AS STRING)
UNION ALL SELECT 'day_of_week', CAST(dayofweek(DATE '2026-03-08') AS STRING) || ' ' || CAST(dayofweek(DATE '2026-03-09') AS STRING) || ' ' || CAST(weekday(DATE '2026-03-09') AS STRING) || ' ' || CAST(extract(DOW_ISO FROM DATE '2026-03-08') AS STRING)
UNION ALL SELECT 'week_of_year', CAST(weekofyear(DATE '2026-01-01') AS STRING)
UNION ALL SELECT 'regexp_like', CAST('abc' RLIKE '^a' AS STRING) || ' ' || CAST(regexp_like('abc', '^a') AS STRING)
UNION ALL SELECT 'regexp_replace_all', regexp_replace('aXbXc', 'X', '-')
UNION ALL SELECT 'split_part', split_part('a,b,c', ',', 1) || ' [' || split_part('a,b,c', ',', 5) || ']'
UNION ALL SELECT 'strpos', CAST(instr('abc', 'c') AS STRING) || ' ' || CAST(position('c', 'abc') AS STRING)
UNION ALL SELECT 'json', get_json_object('{"a":{"b":1}}', '$.a.b') || ' ' || CAST(parse_json('{"a":{"b":1}}'):a.b AS STRING)
UNION ALL SELECT 'unnest_ord', (SELECT array_join(array_agg(CAST(pos + 1 AS STRING)), ',') FROM (SELECT posexplode(array('x','y')) AS (pos, val)))
UNION ALL SELECT 'lambda', CAST(transform(array(1,2), x -> x * 2) AS STRING)
UNION ALL SELECT 'reduce', CAST(reduce(array(1,2,3), 0, (s, x) -> s + x, s -> s) AS STRING) || ' ' || CAST(aggregate(array(1,2,3), 0, (s, x) -> s + x) AS STRING)
UNION ALL SELECT 'from_unixtime', typeof(from_unixtime(0)) || ' ' || typeof(timestamp_seconds(0))
UNION ALL SELECT 'to_unixtime', CAST(unix_timestamp(TIMESTAMP '1970-01-02 00:00:00') AS STRING) || ' ' || CAST(unix_micros(TIMESTAMP '1970-01-02 00:00:00') AS STRING)
UNION ALL SELECT 'session_tz', current_timezone()
UNION ALL SELECT 'count_if', (SELECT CAST(count_if(x > 1) AS STRING) FROM VALUES (1),(2),(3) t(x))
UNION ALL SELECT 'any_value', (SELECT typeof(any_value(x)) FROM VALUES (1) t(x))
UNION ALL SELECT 'max_by', (SELECT max_by(k, v) FROM VALUES ('a',1),('b',2) t(k,v))
UNION ALL SELECT 'string_cmp_case', CAST('a' = 'A' AS STRING)
UNION ALL SELECT 'like_case', CAST('ABC' LIKE 'a%' AS STRING)
UNION ALL SELECT 'struct_type', typeof(named_struct('id', 1, 'name', 'a')) || ' ' || typeof(struct(1, 'a'))
UNION ALL SELECT 'real_type', typeof(1.5) || ' ' || typeof(1.5e0) || ' ' || typeof(CAST(1.5 AS FLOAT))
UNION ALL SELECT 'varbinary', hex(sha2('a', 256))  || ' ' || lower(hex(sha2('a', 256)))
UNION ALL SELECT 'uuid', typeof(uuid())
UNION ALL SELECT 'truncate', CAST(truncate(2.79) AS STRING) || ' ' || CAST(truncate(CAST(2.79 AS DOUBLE), 1) AS STRING)
UNION ALL SELECT 'listagg', (SELECT listagg(x, ',') WITHIN GROUP (ORDER BY x) FROM VALUES ('b'),('a') t(x))
UNION ALL SELECT 'string_pad', '[' || lpad('ab', 1, '0') || ']' || '[' || rpad('ab', 4, 'xy') || ']'
UNION ALL SELECT 'cast_ts_to_date', CAST(CAST(TIMESTAMP '2026-01-01 23:59:59' AS DATE) AS STRING)
UNION ALL SELECT 'cast_str_to_ts', CAST(CAST('2026-01-01' AS TIMESTAMP) AS STRING)
UNION ALL SELECT 'cast_dec_str', CAST(CAST(1.50 AS DECIMAL(10,2)) AS STRING)
UNION ALL SELECT 'cast_double_str', CAST(CAST(1.5 AS DOUBLE) AS STRING) || ' ' || CAST(1e21 AS STRING)
UNION ALL SELECT 'bigint_overflow', CAST(try_add(9223372036854775807, 1) IS NULL AS STRING)
UNION ALL SELECT 'integer_literal_type', typeof(1) || ' ' || typeof(9999999999)
UNION ALL SELECT 'sum_int_type', (SELECT typeof(sum(x)) FROM VALUES (1) t(x))
UNION ALL SELECT 'avg_int_type', (SELECT typeof(avg(x)) || ' ' || CAST(avg(x) AS STRING) FROM VALUES (1), (2) t(x))
UNION ALL SELECT 'count_type', (SELECT typeof(count(*)) FROM VALUES (1) t(x))
UNION ALL SELECT 'string_agg_distinct', (SELECT array_join(array_sort(collect_set(x)), ',') FROM VALUES ('b'),('a'),('b') t(x))
UNION ALL SELECT 'map_keys_sorted', CAST(map_keys(map('b', 1, 'a', 2)) AS STRING)
UNION ALL SELECT 'ts_ms_trunc', CAST(date_trunc('MILLISECOND', TIMESTAMP '2026-01-01 00:00:00.123456') AS STRING)
UNION ALL SELECT 'interval', CAST(DATE '2026-01-31' + INTERVAL 1 MONTH AS STRING)
UNION ALL SELECT 'add_months', CAST(add_months(DATE '2026-01-31', 1) AS STRING)
UNION ALL SELECT 'last_day', CAST(last_day(DATE '2026-02-10') AS STRING)
UNION ALL SELECT 'hash', CAST(xxhash64('a') AS STRING)
UNION ALL SELECT 'if_fn', CAST(if(true, 1, 2) AS STRING) || ' ' || CAST(nullif(1, 1) IS NULL AS STRING)
UNION ALL SELECT 'cast_dec_to_int', CAST(CAST(2.9 AS INT) AS STRING)
UNION ALL SELECT 'cast_str_int_dec', CAST(try_cast('2.9' AS INT) IS NULL AS STRING)
UNION ALL SELECT 'varchar_bounded_cast', '[' || CAST(try_cast('abcdef' AS VARCHAR(3)) AS STRING) || ']'
UNION ALL SELECT 'explode_map', (SELECT array_join(array_agg(k || '=' || CAST(v AS STRING)), ',') FROM (SELECT explode(map('a', 1, 'b', 2)) AS (k, v)))
UNION ALL SELECT 'ansi_mode', CAST(current_setting('spark.sql.ansi.enabled') AS STRING);
