SELECT 'version' AS k, version() AS v;
SELECT 'int_div' AS k, CAST(7 / 2 AS varchar) AS v;
SELECT 'dec_div' AS k, CAST(typeof(CAST(10.00 AS decimal(10,2)) / 3) AS varchar) || ' ' || CAST(CAST(10.00 AS decimal(10,2)) / 3 AS varchar) AS v;
SELECT 'dec_div2' AS k, CAST(typeof(CAST(10.00 AS decimal(12,2)) / CAST(3 AS bigint)) AS varchar) || ' ' || CAST(CAST(10.00 AS decimal(12,2)) / CAST(3 AS bigint) AS varchar) AS v;
SELECT 'avg_dec' AS k, CAST(typeof(avg(x)) AS varchar) || ' ' || CAST(avg(x) AS varchar) AS v FROM (VALUES CAST(1.00 AS decimal(10,2)), CAST(2.00 AS decimal(10,2)), CAST(2.00 AS decimal(10,2))) t(x);
SELECT 'sum_dec' AS k, CAST(typeof(sum(x)) AS varchar) AS v FROM (VALUES CAST(1.00 AS decimal(10,2))) t(x);
SELECT 'concat_null' AS k, coalesce('a' || CAST(NULL AS varchar), '<NULL>') AS v;
SELECT 'round_half' AS k, CAST(round(2.5) AS varchar) || ' ' || CAST(round(-2.5) AS varchar) || ' ' || CAST(round(CAST(2.5 AS double)) AS varchar) AS v;
SELECT 'date_diff_day' AS k, CAST(date_diff('day', TIMESTAMP '2026-01-01 23:00:00', TIMESTAMP '2026-01-02 01:00:00') AS varchar) AS v;
SELECT 'date_diff_month' AS k, CAST(date_diff('month', DATE '2026-01-31', DATE '2026-02-28') AS varchar) AS v;
SELECT 'ts_default_prec' AS k, CAST(typeof(TIMESTAMP '2026-01-01 00:00:00') AS varchar) || ' ' || CAST(typeof(current_timestamp) AS varchar) || ' ' || CAST(typeof(now()) AS varchar) AS v;
SELECT 'ts_literal_p6' AS k, CAST(typeof(TIMESTAMP '2026-01-01 00:00:00.123456') AS varchar) AS v;
SELECT 'char_pad_eq' AS k, CAST(CAST('ab' AS char(4)) = CAST('ab  ' AS char(4)) AS varchar) || ' ' || CAST(length(CAST('ab' AS char(4))) AS varchar) || ' [' || CAST(CAST('ab' AS char(4)) AS varchar) || ']' AS v;
SELECT 'char_vs_varchar' AS k, CAST(CAST('ab' AS char(4)) = 'ab' AS varchar) AS v;
SELECT 'substr_zero' AS k, '[' || substr('abcdef', 0, 3) || ']' AS v;
SELECT 'array_idx' AS k, CAST((ARRAY[10,20,30])[1] AS varchar) AS v;
SELECT 'array_oob' AS k, CAST(element_at(ARRAY[10,20,30], 5) IS NULL AS varchar) AS v;
SELECT 'map_missing' AS k, CAST(element_at(MAP(ARRAY['a'], ARRAY[1]), 'zz') IS NULL AS varchar) AS v;
SELECT 'approx_pct' AS k, CAST(approx_percentile(x, 0.5) AS varchar) FROM (VALUES 1.0, 2.0, 3.0, 4.0) t(x);
SELECT 'approx_pct_type' AS k, CAST(typeof(approx_percentile(x, 0.5)) AS varchar) FROM (VALUES CAST(1.0 AS decimal(10,2))) t(x);
SELECT 'approx_distinct' AS k, CAST(approx_distinct(x) AS varchar) FROM (VALUES 1,2,3,4,5,6,7,8,9,10) t(x);
SELECT 'nulls_order' AS k, array_join(array_agg(x ORDER BY x), ',', 'NULL') AS v FROM (VALUES 2, NULL, 1) t(x);
SELECT 'nulls_order_desc' AS k, array_join(array_agg(x ORDER BY x DESC), ',', 'NULL') AS v FROM (VALUES 2, NULL, 1) t(x);
SELECT 'array_agg_null' AS k, CAST(cardinality(array_agg(x)) AS varchar) FROM (VALUES 1, NULL) t(x);
SELECT 'greatest_null' AS k, CAST(greatest(1, NULL) IS NULL AS varchar) AS v;
SELECT 'mod_neg' AS k, CAST(mod(-7, 3) AS varchar) || ' ' || CAST(-7 % 3 AS varchar) AS v;
SELECT 'div_zero' AS k, CAST(try(1/0) IS NULL AS varchar) AS v;
SELECT 'cast_bad' AS k, CAST(try_cast('x' AS integer) IS NULL AS varchar) AS v;
SELECT 'format_datetime' AS k, format_datetime(TIMESTAMP '2026-03-07 14:05:09', 'yyyy-MM-dd HH:mm E') AS v;
SELECT 'date_format' AS k, date_format(TIMESTAMP '2026-03-07 14:05:09', '%Y-%m-%d %H:%i %W') AS v;
SELECT 'date_trunc_week' AS k, CAST(date_trunc('week', DATE '2026-03-08') AS varchar) AS v;
SELECT 'day_of_week' AS k, CAST(day_of_week(DATE '2026-03-08') AS varchar) || ' ' || CAST(dow(DATE '2026-03-09') AS varchar) AS v;
SELECT 'week_of_year' AS k, CAST(week(DATE '2026-01-01') AS varchar) AS v;
SELECT 'regexp_like' AS k, CAST(regexp_like('abc', '^a') AS varchar) AS v;
SELECT 'regexp_replace_all' AS k, regexp_replace('aXbXc', 'X', '-') AS v;
SELECT 'split_part' AS k, split_part('a,b,c', ',', 1) || ' ' || coalesce(split_part('a,b,c', ',', 5), '<NULL>') AS v;
SELECT 'strpos' AS k, CAST(strpos('abc', 'c') AS varchar) AS v;
SELECT 'json' AS k, json_extract_scalar('{"a":{"b":1}}', '$.a.b') AS v;
SELECT 'unnest_ord' AS k, array_join(array_agg(CAST(o AS varchar) ORDER BY o), ',') AS v FROM UNNEST(ARRAY['x','y']) WITH ORDINALITY AS t(v, o);
SELECT 'lambda' AS k, CAST(transform(ARRAY[1,2], x -> x * 2) AS varchar) AS v;
SELECT 'reduce' AS k, CAST(reduce(ARRAY[1,2,3], 0, (s, x) -> s + x, s -> s) AS varchar) AS v;
SELECT 'from_unixtime' AS k, CAST(typeof(from_unixtime(0)) AS varchar) AS v;
SELECT 'to_unixtime' AS k, CAST(to_unixtime(TIMESTAMP '1970-01-02 00:00:00') AS varchar) AS v;
SELECT 'current_date_type' AS k, CAST(typeof(current_date) AS varchar) || ' ' || CAST(typeof(localtimestamp) AS varchar) AS v;
SELECT 'at_tz' AS k, CAST(typeof(TIMESTAMP '2026-01-01 00:00:00 UTC') AS varchar) AS v;
SELECT 'bool_agg' AS k, CAST(bool_or(x) AS varchar) FROM (VALUES true, false) t(x);
SELECT 'count_if' AS k, CAST(count_if(x > 1) AS varchar) FROM (VALUES 1,2,3) t(x);
SELECT 'arbitrary' AS k, CAST(typeof(arbitrary(x)) AS varchar) FROM (VALUES 1) t(x);
SELECT 'max_by' AS k, max_by(k, v) FROM (VALUES ('a',1),('b',2)) t(k,v);
SELECT 'string_cmp_case' AS k, CAST('a' = 'A' AS varchar) AS v;
SELECT 'like_case' AS k, CAST('ABC' LIKE 'a%' AS varchar) AS v;
SELECT 'row_type' AS k, CAST(typeof(ROW(1, 'a')) AS varchar) AS v;
SELECT 'row_field' AS k, CAST(CAST(ROW(1, 'a') AS ROW(id integer, name varchar)).name AS varchar) AS v;
SELECT 'real_type' AS k, CAST(typeof(REAL '1.5') AS varchar) || ' ' || CAST(typeof(1.5) AS varchar) || ' ' || CAST(typeof(1.5e0) AS varchar) AS v;
SELECT 'varbinary' AS k, to_hex(sha256(to_utf8('a'))) AS v;
SELECT 'uuid' AS k, CAST(typeof(uuid()) AS varchar) AS v;
SELECT 'ipaddr' AS k, CAST(typeof(IPADDRESS '10.0.0.1') AS varchar) AS v;
SELECT 'truncate' AS k, CAST(truncate(2.79) AS varchar) || ' ' || CAST(truncate(CAST(2.79 AS double), 1) AS varchar) AS v;
SELECT 'percentile_exact' AS k, CAST(approx_percentile(x, 0.5) AS varchar) AS v FROM (VALUES 1,2,3,4,100) t(x);
SELECT 'listagg' AS k, listagg(x, ',') WITHIN GROUP (ORDER BY x) AS v FROM (VALUES 'b','a') t(x);
SELECT 'string_pad' AS k, '[' || lpad('ab', 1, '0') || ']' || '[' || rpad('ab', 4, 'xy') || ']' AS v;
SELECT 'cast_ts_to_date' AS k, CAST(CAST(TIMESTAMP '2026-01-01 23:59:59' AS date) AS varchar) AS v;
SELECT 'cast_str_to_ts' AS k, CAST(CAST('2026-01-01' AS timestamp) AS varchar) AS v;
SELECT 'cast_dec_str' AS k, CAST(CAST(1.50 AS decimal(10,2)) AS varchar) AS v;
SELECT 'cast_double_str' AS k, CAST(CAST(1.5 AS double) AS varchar) || ' ' || CAST(1e21 AS varchar) AS v;
SELECT 'bigint_overflow' AS k, CAST(try(9223372036854775807 + 1) IS NULL AS varchar) AS v;
SELECT 'integer_literal_type' AS k, CAST(typeof(1) AS varchar) || ' ' || CAST(typeof(9999999999) AS varchar) AS v;
SELECT 'sum_int_type' AS k, CAST(typeof(sum(x)) AS varchar) FROM (VALUES 1) t(x);
SELECT 'avg_int_type' AS k, CAST(typeof(avg(x)) AS varchar) || ' ' || CAST(avg(x) AS varchar) FROM (VALUES 1, 2) t(x);
SELECT 'count_type' AS k, CAST(typeof(count(*)) AS varchar) FROM (VALUES 1) t(x);
SELECT 'string_agg_distinct' AS k, array_join(array_agg(DISTINCT x ORDER BY x), ',') FROM (VALUES 'b','a','b') t(x);
SELECT 'map_agg' AS k, CAST(map_agg(k, v) AS json) FROM (VALUES ('a',1)) t(k,v);
SELECT 'map_keys_sorted' AS k, CAST(map_keys(MAP(ARRAY['b','a'], ARRAY[1,2])) AS varchar) AS v;
SELECT 'ts_ms_trunc' AS k, CAST(CAST(TIMESTAMP '2026-01-01 00:00:00.123456' AS timestamp(3)) AS varchar) AS v;
SELECT 'interval' AS k, CAST(DATE '2026-01-31' + INTERVAL '1' MONTH AS varchar) AS v;
SELECT 'date_add' AS k, CAST(date_add('month', 1, DATE '2026-01-31') AS varchar) AS v;
SELECT 'last_day' AS k, CAST(last_day_of_month(DATE '2026-02-10') AS varchar) AS v;
SELECT 'hash' AS k, CAST(xxhash64(to_utf8('a')) AS varchar) AS v;
SELECT 'if_fn' AS k, CAST(if(true, 1, 2) AS varchar) || ' ' || CAST(nullif(1, 1) IS NULL AS varchar) AS v;
SELECT 'try_cast_int_from_dec' AS k, CAST(CAST(2.9 AS integer) AS varchar) AS v;
SELECT 'cast_str_int_dec' AS k, CAST(try_cast('2.9' AS integer) IS NULL AS varchar) AS v;
SELECT 'varchar_bounded_cast' AS k, '[' || CAST(CAST('abcdef' AS varchar(3)) AS varchar) || ']' AS v;
SELECT 'grouping_sets' AS k, CAST(count(*) AS varchar) FROM (VALUES ('a',1),('b',2)) t(k,v) GROUP BY GROUPING SETS ((k), ()) ORDER BY 1 LIMIT 1;
SELECT 'qualify_absent' AS k, 'trino has no QUALIFY' AS v;
SELECT 'approx_set' AS k, CAST(cardinality(approx_set(x)) AS varchar) FROM (VALUES 1,2,3) t(x);
SELECT 'row_number_ties' AS k, 'n/a' AS v;
