-- Lakebase (Postgres) shape of the loan_servicing operational unit, converted from the
-- Sybase ASE DDL in ts-tsql-sybase-legacy-db/schema. Run against the migration branch
-- database only (never the production branch): psql "$LAKEBASE_MIGRATION_DSN" -f target_ddl.sql
--
-- Conversions: INT IDENTITY -> GENERATED BY DEFAULT AS IDENTITY (explicit ids load, sequence
-- is restarted by the loader); MONEY -> NUMERIC(19,4); DATETIME/datetime2 -> TIMESTAMP(6);
-- CHAR(n) kept; TEXT/VARCHAR(MAX) -> TEXT. Clustered/nonclustered has no Postgres meaning.

CREATE SCHEMA IF NOT EXISTS loan_servicing;
SET search_path = loan_servicing;

CREATE TABLE borrowers (
    borrower_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ssn_hash        VARCHAR(64)   NOT NULL,
    first_name      VARCHAR(50)   NOT NULL,
    last_name       VARCHAR(50)   NOT NULL,
    date_of_birth   TIMESTAMP(6),
    credit_score    SMALLINT,
    borrower_type   CHAR(1)       NOT NULL,
    state_code      CHAR(2)       NOT NULL,
    phone_number    VARCHAR(15),
    email           VARCHAR(100),
    employer_name   VARCHAR(100),
    annual_income   NUMERIC(19,4),
    created_date    TIMESTAMP(6)  NOT NULL DEFAULT now(),
    modified_date   TIMESTAMP(6)  NOT NULL DEFAULT now(),
    CONSTRAINT pk_borrowers PRIMARY KEY (borrower_id)
);
CREATE INDEX ix_borrowers_ssn   ON borrowers (ssn_hash);
CREATE INDEX ix_borrowers_state ON borrowers (state_code, borrower_type);

CREATE TABLE loans (
    loan_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    borrower_id         INTEGER       NOT NULL,
    loan_number         VARCHAR(20)   NOT NULL,
    loan_type           CHAR(4)       NOT NULL,
    loan_purpose        CHAR(1)       NOT NULL,
    original_balance    NUMERIC(19,4) NOT NULL,
    current_balance     NUMERIC(19,4) NOT NULL,
    interest_rate       NUMERIC(6,4)  NOT NULL,
    term_months         INTEGER       NOT NULL,
    origination_date    TIMESTAMP(6)  NOT NULL,
    first_payment_date  TIMESTAMP(6)  NOT NULL,
    maturity_date       TIMESTAMP(6)  NOT NULL,
    loan_status         CHAR(2)       NOT NULL,
    days_past_due       INTEGER       NOT NULL DEFAULT 0,
    past_due_amount     NUMERIC(19,4) NOT NULL DEFAULT 0,
    escrow_balance      NUMERIC(19,4) NOT NULL DEFAULT 0,
    late_fee_balance    NUMERIC(19,4) NOT NULL DEFAULT 0,
    late_fee_assessed   INTEGER       NOT NULL DEFAULT 0,
    last_fee_date       TIMESTAMP(6),
    servicer_id         INTEGER       NOT NULL,
    investor_code       VARCHAR(10),
    property_state      CHAR(2)       NOT NULL,
    property_value      NUMERIC(19,4),
    ltv                 NUMERIC(6,4),
    note_text           TEXT,
    created_date        TIMESTAMP(6)  NOT NULL DEFAULT now(),
    modified_date       TIMESTAMP(6)  NOT NULL DEFAULT now(),
    CONSTRAINT pk_loans PRIMARY KEY (loan_id),
    CONSTRAINT fk_loans_borrower FOREIGN KEY (borrower_id) REFERENCES borrowers (borrower_id),
    CONSTRAINT ck_loans_type   CHECK (loan_type IN ('CONV', 'FHA', 'VA', 'USDA')),
    CONSTRAINT ck_loans_status CHECK (loan_status IN ('AC', 'DL', 'FC', 'PO', 'CO', 'BK'))
);
CREATE INDEX ix_loans_borrower ON loans (borrower_id);
CREATE INDEX ix_loans_status   ON loans (loan_status, days_past_due);
CREATE INDEX ix_loans_servicer ON loans (servicer_id, loan_status);
CREATE UNIQUE INDEX ix_loans_number ON loans (loan_number);
CREATE INDEX ix_loans_portfolio_cover ON loans (loan_status, borrower_id)
    INCLUDE (loan_id, loan_type, current_balance, interest_rate, days_past_due,
             past_due_amount, investor_code, property_state, ltv);

CREATE TABLE payments (
    payment_id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_id         INTEGER       NOT NULL,
    payment_date    TIMESTAMP(6)  NOT NULL,
    effective_date  TIMESTAMP(6)  NOT NULL,
    principal_amt   NUMERIC(19,4) NOT NULL DEFAULT 0,
    interest_amt    NUMERIC(19,4) NOT NULL DEFAULT 0,
    escrow_amt      NUMERIC(19,4) NOT NULL DEFAULT 0,
    late_fee_amt    NUMERIC(19,4) NOT NULL DEFAULT 0,
    total_amt       NUMERIC(19,4) NOT NULL,
    payment_type    CHAR(3)       NOT NULL,
    payment_method  CHAR(3),
    batch_id        INTEGER,
    reversal_flag   CHAR(1)       NOT NULL DEFAULT 'N',
    created_date    TIMESTAMP(6)  NOT NULL DEFAULT now(),
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT fk_payments_loan FOREIGN KEY (loan_id) REFERENCES loans (loan_id),
    CONSTRAINT ck_payments_type CHECK (payment_type IN ('REG', 'EXT', 'PIF', 'NSF', 'MOD', 'ESC', 'FEE'))
);
CREATE INDEX ix_payments_loan       ON payments (loan_id, payment_date);
CREATE INDEX ix_payments_batch      ON payments (batch_id);
CREATE INDEX ix_payments_date_range ON payments (payment_date, loan_id)
    INCLUDE (total_amt, payment_type, reversal_flag);

CREATE TABLE escrow_accounts (
    escrow_id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_id             INTEGER       NOT NULL,
    escrow_type         CHAR(3)       NOT NULL,
    monthly_amount      NUMERIC(19,4) NOT NULL,
    current_balance     NUMERIC(19,4) NOT NULL DEFAULT 0,
    target_balance      NUMERIC(19,4) NOT NULL DEFAULT 0,
    last_disbursement   TIMESTAMP(6),
    next_due_date       TIMESTAMP(6),
    shortage_flag       CHAR(1)       NOT NULL DEFAULT 'N',
    created_date        TIMESTAMP(6)  NOT NULL DEFAULT now(),
    modified_date       TIMESTAMP(6)  NOT NULL DEFAULT now(),
    CONSTRAINT pk_escrow PRIMARY KEY (escrow_id),
    CONSTRAINT fk_escrow_loan FOREIGN KEY (loan_id) REFERENCES loans (loan_id)
);
CREATE INDEX ix_escrow_loan ON escrow_accounts (loan_id, escrow_type);

CREATE TABLE loan_modifications (
    modification_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_id             INTEGER       NOT NULL,
    modification_type   CHAR(3)       NOT NULL,
    effective_date      TIMESTAMP(6)  NOT NULL,
    expiration_date     TIMESTAMP(6),
    original_rate       NUMERIC(6,4),
    modified_rate       NUMERIC(6,4),
    original_term       INTEGER,
    modified_term       INTEGER,
    deferred_amount     NUMERIC(19,4),
    status              CHAR(1)       NOT NULL,
    created_date        TIMESTAMP(6)  NOT NULL DEFAULT now(),
    CONSTRAINT pk_loan_mods PRIMARY KEY (modification_id),
    CONSTRAINT fk_loan_mods_loan FOREIGN KEY (loan_id) REFERENCES loans (loan_id)
);
CREATE INDEX ix_loan_mods_loan ON loan_modifications (loan_id, status);
